# Logistic Regression

In [4]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
x = np.array([1.1, 4.1, 2.7, 3.9, 7.1, 1.3, 9.7, 0.7, 3.4, 6.0]).reshape(
-1,1)
y = np.array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [7]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(x,y)


In [10]:
model.classes_

array([0, 1])

In [11]:
model.intercept_

array([-0.97024993])

In [12]:
model.coef_

array([[0.24301357]])

In [13]:
model.predict(x)

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

In [14]:
model.score(x,y)

0.8

In [15]:
confusion_matrix(y,model.predict(x))

array([[5, 1],
       [1, 3]], dtype=int64)